spring:
  application:
    name: springboot-quartz-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    password: xjh12345678
    username: scott
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
server:
  port: 8090
  servlet:
    context-path: /myApplication
mybatis:
  type-aliases-package: com.master.dao
  mapper-locations: classpath:mapper/*.xml

